config/routes.rb
Rails.application.routes.draw do
  resources :bundles do
    collection do
      get 'owned'
    end
  end

  devise_for :users
  resources :notes do
    collection do
      get 'owned'
    end
    member do
      patch 'add_to_bundle'
    end
  end

   root 'notes#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #user ||= User.new # guest user (not logged in)
    can :read, Note do |note|
      note.read_permission(user)
    end

    can :manage, Note do |note|
      note.user.eql?(user) or note.crud_permission(user)
    end
    if user.admin?
      can :manage, :all
    end
    can :create, Note
    can :create, Bundle
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/bundle.rb
class Bundle < ActiveRecord::Base
  #Relationship
  belongs_to :user
  has_many :note_bundles
  has_many :notes, through: :note_bundles
  has_many :permissions, as: :entity
  #Callbacks
  after_create :give_permission_to_creator
  #Validations
  #validates :notes, presence: true

  def crate_bundle(user, note_ids)
  end
  
  private
  def give_permission_to_creator
    self.permissions.create(user: self.user, level: 2)
  end
end

app/models/note.rb
class Note < ActiveRecord::Base
  #Relationships
  belongs_to :user
  has_many :permissions, as: :entity
  has_many :note_bundles
  has_many :bundles, through: :note_bundles
  #callbacks
  after_create :give_permission_to_creator
  #validations
  validates :titel, presence: true, length: { minimum: 1, maaximum: 100 }
  validates :description, presence: true, length: { minimum: 1, maximum: 10000 }
  
  def crud_permission(user)
    permission = self.permissions.where(user: user).first
    unless permission.nil?
      return true if permission.level = 2
    end
  end

  def read_permission(user)
    permission = self.permissions.where(user: user).first
    unless permission.nil?
      return true if permission.level >= 1
    end
  end

  def bundles_not_part_of(user)
    bundles_part_of = self.bundles
    user_bundles = user.bundles
    return user_bundles - bundles_part_of
  end

 
  private
  def give_permission_to_creator
    self.permissions.create(user: self.user, level: 2)
  end
end

app/models/note_bundle.rb
class NoteBundle < ActiveRecord::Base
  belongs_to :bundle
  belongs_to :note
end

app/models/permission.rb
class Permission < ActiveRecord::Base
  belongs_to :user
  belongs_to :entity, polymorphic: true
  VALUES = {DENIED: 0, READ: 1, WRITE: 2}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  #Relationship
  has_many :notes
  has_many :bundles
  has_many :permissions, as: :entity
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/bundles_controller.rb
class BundlesController < ApplicationController
  before_action :set_bundle, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource :except => :create

  # GET /bundles
  # GET /bundles.json
  def index
    @bundles = Bundle.all
  end

  # GET /bundles/1
  # GET /bundles/1.json
  def show
  end

  # GET /bundles/new
  def new
    @bundle = Bundle.new
  end

  # GET /bundles/1/edit
  def edit
  end

  # POST /bundles
  # POST /bundles.json
  def create
    @bundle = Bundle.new(bundle_params)
    @bundle.user = current_user
    respond_to do |format|
      if @bundle.save
        format.html { redirect_to @bundle, notice: 'Bundle was successfully created.' }
        format.json { render :show, status: :created, location: @bundle }
      else
        format.html { render :new }
        format.json { render json: @bundle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bundles/1
  # PATCH/PUT /bundles/1.json
  def update
    respond_to do |format|
      if @bundle.update(bundle_params)
        format.html { redirect_to @bundle, notice: 'Bundle was successfully updated.' }
        format.json { render :show, status: :ok, location: @bundle }
      else
        format.html { render :edit }
        format.json { render json: @bundle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bundles/1
  # DELETE /bundles/1.json
  def destroy
    @bundle.destroy
    respond_to do |format|
      format.html { redirect_to bundles_url, notice: 'Bundle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def owned
    @bundles = current_user.bundles
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bundle
      @bundle = Bundle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bundle_params
      params.require(:bundle).permit(:user_id)
    end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy, :add_to_bundle]
  load_and_authorize_resource :except => :create

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
    @bundles = @note.bundles_not_part_of(current_user)
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)
    @note.user = current_user
    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def owned
    @notes = current_user.notes
  end

  def add_to_bundle
   @bundle = Bundle.find(params[:bundle])
   @note.bundles<< @bundle
    print(@note)
    print(@bundle)
    redirect_to @note, notice: "Note was successfully added to #{@bundle.name}"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:titel, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bundles_helper.rb
module BundlesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/bundles/_form.html.erb
<%= form_for(@bundle) do |f| %>
  <% if @bundle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bundle.errors.count, "error") %> prohibited this bundle from being saved:</h2>

      <ul>
      <% @bundle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bundles/delete.html.erb
<h1>Bundles#delete</h1>
<p>Find me in app/views/bundles/delete.html.erb</p>

app/views/bundles/edit.html.erb
<h1>Editing Note</h1>

<%= render 'form' %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/bundles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Notes</h1>

<table>
  <thead>
    <tr>
      <th>Titel</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bundles.each do |bundle| %>
      <% bundle.notes.each do |note| %>
        <tr>
          <td><%= note.titel %></td>
          <td><%= note.description %></td>
          <td><%= note.user.email %></td>
          <td><%= link_to 'Show', note %></td>
          <% if can? :crud, bundle %>
            <td><%= link_to 'Edit', edit_bundle_path(bundle) %></td>
            <td><%= link_to 'Destroy', bundle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bundle', new_bundle_path %>
<%= link_to 'My Bundles', owned_bundles_path %>

app/views/bundles/new.html.erb
<h1>New Note</h1>

<%= render 'form' %>

<%= link_to 'Back', notes_path %>

app/views/bundles/owned.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Notes</h1>

<table>
  <thead>
    <tr>
      <th>Titel</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <h2>  Notes Created </h2>
    <% @notes.each do |note| %>
      <tr>
        <td><%= note.titel %></td>
        <td><%= note.description %></td>
        <td><%= note.user.email %></td>
        <td><%= link_to 'Show', note %></td>
        <% if can? :crud, note %>
          <td><%= link_to 'Edit', edit_note_path(note) %></td>
          <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Note', new_note_path %>

app/views/bundles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @bundle.name %>
</p>


<%= link_to 'Edit', edit_bundle_path(@bundle) %> |
<%= link_to 'Back', bundles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Notes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>  
  <%= csrf_meta_tags %>
</head>
<body>
  <%= link_to 'Logout', destroy_user_session_path, method: :delete%>
<%= yield %>

</body>
</html>

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titel %><br>
    <%= f.text_field :titel %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Notes</h1>

<table>
  <thead>
    <tr>
      <th>Titel</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= note.titel %></td>
        <td><%= note.description %></td>
        <td><%= note.user.email %></td>
        <td><%= link_to 'Show', note %></td>
        <% if can? :crud, note %>
          <td><%= link_to 'Edit', edit_note_path(note) %></td>
          <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Note', new_note_path %>

app/views/notes/owned.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Notes</h1>

<table>
  <thead>
    <tr>
      <th>Titel</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <h2>  Notes Created </h2>
    <% @notes.each do |note| %>
      <tr>
        <td><%= note.titel %></td>
        <td><%= note.description %></td>
        <td><%= note.user.email %></td>
        <td><%= link_to 'Show', note %></td>
        <% if can? :crud, note %>
          <td><%= link_to 'Edit', edit_note_path(note) %></td>
          <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Note', new_note_path %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Titel:</strong>
  <%= @note.titel %>
</p>

<p>
  <strong>Description:</strong>
  <%= @note.description %>
</p>
<p>
  <strong>Bundles part of:</strong>
  <% @note.bundles.each do |bundle| %>
    <%= bundle.name %>
  <% end %>
</p>
<% unless @bundles.empty? %>
  <%= form_for(@note, url: add_to_bundle_note_path) do |f| %>
    <% bundles_array = @bundles.map { |bundle| [bundle.name, bundle.id] } %>
    <%= select_tag(:bundle, options_for_select(bundles_array)) %>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
<% end %>

<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>